[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 13.0
[shell]
program = "$HOME\scoop\apps\msys2\current\msys2_shell.cmd"
args = ["-defterm", "-here", "-use-full-path", "-no-start", "-mingw64"]
